---

# Gather facts specific to the Raspberry Pi platform
- include: raspi-facts.yml
- include: linux-facts.yml

# Basic hostname setup
- name: Get MAC address
  debug: 
    msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
  tags:
    - raspi
    - sw

- name: store MAC address
  set_fact:
    my_macaddr: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
  tags:
    - raspi
    - sw

- name: store system configuration
  set_fact:
    myconfig: "{{ macaddrs[my_macaddr] }}"
  tags:
    - raspi
    - sw

- name: set hostname
  become: yes
  shell: "raspi-config nonint do_hostname {{ myconfig.hostname }}"
  when: raspi_hostname != myconfig.hostname

- name: update /etc/hosts with new hostname
  become: yes
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}"
    line="{{ ansible_default_ipv4.address }}{{'\t'}}{{ myconfig.hostname }}.{{ myconfig.domain }}{{'\t'}}{{ myconfig.hostname }}"
    state=present

- name: get rid of default 127.0.1.1 binding
  become: yes
  lineinfile:
    dest=/etc/hosts
    regexp="^127.0.1.1"
    state=absent

# Set timezone
- name: set timezone
  become: yes
  command: "timedatectl set-timezone {{ myconfig.timezone }}"
  when: linux_tz != myconfig.timezone

# Set locale
- name: set locale
  become: yes
  command: "raspi-config nonint do_change_locale {{ myconfig.locale }}"
  when: "'locale' in myconfig and linux_locale != myconfig.locale"

# Other tasks
- include: software.yml
- include: raspi-config.yml
- include: linux-config.yml
- include: log2ram.yml
- include: pihole.yml
  when: "raspi_type == '1'"
- include: docker.yml
  when: "raspi_type == '2' or raspi_type == '3'"