---
- name: "Download Pi-Hole installer"
  get_url:
      url: https://install.pi-hole.net
      dest: ~/install-pihole.sh
      mode: 0740
  tags: pihole

- name: Install Pi-Hole
  shell: "~/install-pihole.sh --unattended"
  register: dbg_install_pihole
  tags: pihole

- name: Set PiHole to update every week
  become: True
  replace:
    path: /etc/cron.d/pihole
    regexp: '^#(.*updatePihole.*)$'
    replace: '\1'
    backup: yes
  tags: admin
  
  # - name: 'Reboot'
  #   shell: sleep 2 && reboot
  #   async: 1
  #   poll: 0
  #   ignore_errors: true
  #   tags: pihole
  #
  # - name: "Wait for Raspberry PI to come back"
  #   local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
  #   become: false