---
- name: "Download Pi-Hole installer"
  get_url:
      url: https://install.pi-hole.net
      dest: ~/install-pihole.sh
      mode: 0740
  tags: pihole

- name: Create pihole configuration directory
  become: yes
  file:
    name="{{ fspath_pihole_config }}"
    state=directory
    owner="{{ user_pihole }}"
    group="{{ group_pihole }}"
    mode=0755
  tags: pihole

- name: Set static IP configuration
  become: yes
  template:
    src="etc_network_interfaces.j2"
    dest="/etc/network/interfaces"
    owner=root
    group=root
    mode=0644
  tags: pihole

- name: Set default DNS
  become: yes
  template:
    src="etc_resolf.conf.j2"
    dest="/etc/resolv.conf"
    owner=root
    group=root
    mode=0644
  tags: admin

- name: Create pihole configuration
  become: yes
  template:
    src="setupVars.conf.j2"
    dest="{{ fspath_pihole_config }}/setupVars.conf"
    owner=root
    group=root
    mode=0644
  tags: pihole

- name: Install Pi-Hole
  become: yes
  shell: "/home/pi/install-pihole.sh --unattended"
  register: dbg_install_pihole
  tags: pihole

- name: Set PiHole to update every week
  become: yes
  replace:
    path: /etc/cron.d/pihole
    regexp: '^#(.*updatePihole.*)$'
    replace: '\1'
    backup: yes
  tags: admin

  # - name: 'Reboot'
  #   shell: sleep 2 && reboot
  #   async: 1
  #   poll: 0
  #   ignore_errors: true
  #   tags: pihole
  #
  # - name: "Wait for Raspberry PI to come back"
  #   local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
  #   become: false
