---
# update and upgrade apt packages
- name: update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400

# Uninstall Raspbian bloat
# - name: remove raspbian bloat
#   become: yes
#   apt:
#     name="{{ packages }}"
#     state=absent
#   vars:
#     packages:
#       - wolfram-engine
#       - libreoffice*
#       - scratch
#       - minecraft-pi
#       - python-minecraftpi
#       - python3-minecraftpi
#       - sonic-pi
#       - dillo
#       - gpicview
#       - penguinspuzzle
#   tags:
#     - sw

# Install required software
- name: install basic software environment
  become: yes
  apt:
    name="{{ packages }}"
    state=present
    update_cache=no
  vars:
    packages:
      - git
      - python-apt  
      - python-pip
      - wget
      - ca-certificates
      - gnupg-agent
      - curl
      - apt-transport-https
      - software-properties-common
      - libffi-dev
      - libssl-dev
      - python3
  tags:
    - sw

